# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'chege' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire','~>4.1'
	pod 'Kingfisher'
	pod 'MJRefresh'
	pod 'MJExtension'
	pod 'SnapKit'
    pod 'SwiftyJSON'
  # Pods for chege

end
